sudo: false
language: node_js
node_js:
  - '0.12'
  - '0.10'
script: "npm test"
# Send coverage data to Coveralls
after_script: "cat ./test/coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
